name: SaveToRoblox
author: 'tenx29'
description: 'Saves a place file to Roblox'
inputs:
  api-key:
    description: 'The API key to use'
    required: true
  universeId:
    description: 'The universe ID to save to'
    required: true
  place-id:
    description: 'The place ID to save to'
    required: true
  version-type:
    type: choice
    description: 'The version type to save as'
    required: true
    default: Saved
    options:
    - Saved
    - Published
  place-file:
    description: 'The .rbxlx place file to save'
    required: true
outputs:
  versionNumber:
    description: 'The version number of the saved place'
runs:
  using: 'node16'
  main: 'dist/index.js'